baseURL = "https://www.rninsurance.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = "true"
languageCode = "en-us"
[[menu.main]]
name = "Insurance Plans"
weight = 2
[[menu.main]]
name = "About"
url = "/about"
weight = 3
[[menu.main]]
name = "Resources"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
